title: Infinite Federation
tagline: "Design. Deploy. Govern. Query."
description: "Trino & Starburst consulting—from zero to production, safely and fast."
url: "https://infinitefederation.github.io"
baseurl: ""
logo: /assets/img/logo.png
permalink: /:title/

# Use GitHub Pages' default Jekyll (no custom theme). We'll use custom layouts/CSS.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  case_studies:
    output: true
    permalink: /case-studies/:name/

defaults:
  - scope: { path: "" }
    values:
      layout: default
      author_profile: false
      toc: false
