title: Infinite Federation
tagline: "Powering Data Mesh for Enterprises & Entrepreneurs"
description: "Federated data architectures built on Trino and Starburst—turning fragmentation into one mesh, one experience."
url: "https://infed.io"
baseurl: ""
logo: /assets/img/logo.png
permalink: /:title/

# Use GitHub Pages' default Jekyll (no custom theme). We'll use custom layouts/CSS.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  case_studies:
    output: true
    permalink: /case-studies/:name/

defaults:
  - scope: { path: "" }
    values:
      layout: default
      author_profile: false
      toc: false
